version: "3.8"

services:
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamo
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./.data/dynamodb:/home/dynamodblocal/data"
    ports:
      - 8000:8000
